# Generated by Django 3.1.6 on 2023-09-15 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('base', models.CharField(choices=[('thin-crust', 'Thin Crust'), ('normal', 'Normal'), ('cheese-burst', 'Cheese Burst')], max_length=15)),
                ('cheese', models.CharField(choices=[('mozzarella', 'Mozzarella'), ('cheddar', 'Cheddar'), ('parmesan', 'Parmesan'), ('gouda', 'Gouda')], max_length=15)),
                ('toppings', models.JSONField(choices=[('pepperoni', 'Pepperoni'), ('mushrooms', 'Mushrooms'), ('bell-peppers', 'Bell Peppers'), ('olives', 'Olives'), ('onions', 'Onions'), ('tomatoes', 'Tomatoes'), ('sausage', 'Sausage')], default=list)),
                ('price', models.DecimalField(decimal_places=2, default=100.0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Placed', 'Placed'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Placed', max_length=15)),
                ('ordered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pizzas', models.ManyToManyField(blank=True, to='app.Pizza')),
            ],
        ),
    ]
